import React from 'react';
import { format } from 'date-fns';

export const PrintableReportTemplate = React.forwardRef<HTMLDivElement, { data: any }>(({ data }, ref) => {
  if (!data) return null;

  const PageHeader = () => (
    <div className="flex justify-between items-start border-b-4 border-luxury-emerald-950 pb-6 mb-8">
      <div>
        <h1 className="text-4xl font-serif font-bold text-luxury-emerald-950">Camilla Banquet Hotel</h1>
        <p className="text-luxury-gold-600 font-bold tracking-widest text-sm uppercase mt-1">Management Performance Report</p>
        <p className="text-stone-500 text-xs mt-2">123 Luxury Avenue, Kurunegala, Sri Lanka</p>
      </div>
      <div className="text-right">
        <p className="text-xs font-bold text-stone-500 uppercase tracking-widest">Report Generated</p>
        <p className="text-sm font-semibold">{format(new Date(), 'PPpp')}</p>
        <p className="text-[10px] text-stone-400 mt-1">ID: REP-{Date.now().toString().slice(-6)}</p>
        <p className="text-[10px] text-stone-400">Generated by: HallCamilla System</p>
      </div>
    </div>
  );

  const PageFooter = ({ page }: { page: number }) => (
    <div className="absolute bottom-8 left-8 right-8 pt-4 border-t border-stone-200 flex justify-between text-xs text-stone-400">
      <p className="font-bold uppercase tracking-widest text-stone-500">Confidential Business Report</p>
      <p>Page {page} of 4</p>
    </div>
  );

  return (
    <div className="w-[210mm] bg-white text-stone-900 font-sans print-container" ref={ref}>
      
      {/* ================= PAGE 1 ================= */}
      <div className="relative h-[297mm] w-full p-8 bg-white overflow-hidden box-border">
        <PageHeader />

        {/* Section 1: Executive Summary */}
        <div className="mb-10">
          <h2 className="text-2xl font-serif font-bold text-luxury-emerald-950 border-b border-stone-200 pb-2 mb-4">1. Executive Summary</h2>
          <div className="grid grid-cols-4 gap-4">
            {[
              { label: 'Total Revenue', value: `LKR ${data.kpis.totalRevenue.toLocaleString()}` },
              { label: 'Total Bookings', value: data.kpis.totalBookings },
              { label: 'Completed Events', value: data.kpis.completedEvents },
              { label: 'Pending Bookings', value: data.kpis.pendingBookings },
              { label: 'Total Customers', value: data.kpis.totalCustomers },
              { label: 'Cancellations', value: data.kpis.cancelledBookings },
              { label: 'Active Halls', value: data.kpis.activeHalls },
              { label: 'Active Packages', value: data.kpis.activePackages }
            ].map((kpi, i) => (
              <div key={i} className="bg-stone-50 p-4 rounded border border-stone-200">
                <p className="text-[10px] uppercase font-bold text-stone-500 tracking-wider mb-1">{kpi.label}</p>
                <p className="text-xl font-bold text-luxury-emerald-950">{kpi.value}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Section 2 & 3: Booking Status & Revenue */}
        <div className="grid grid-cols-2 gap-8 mb-10">
          <div>
            <h2 className="text-xl font-serif font-bold text-luxury-emerald-950 border-b border-stone-200 pb-2 mb-4">2. Booking Status Summary</h2>
            <table className="w-full text-sm">
              <thead className="bg-luxury-emerald-950 text-white">
                <tr>
                  <th className="p-2 text-left">Status</th>
                  <th className="p-2 text-right">Count</th>
                  <th className="p-2 text-right">Percentage</th>
                </tr>
              </thead>
              <tbody>
                {data.bookingStatus.map((s: any, i: number) => (
                  <tr key={i} className="border-b border-stone-100">
                    <td className="p-2 font-semibold text-stone-700">{s.status}</td>
                    <td className="p-2 text-right">{s.count}</td>
                    <td className="p-2 text-right font-bold text-luxury-gold-600">{s.percentage}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div>
            <h2 className="text-xl font-serif font-bold text-luxury-emerald-950 border-b border-stone-200 pb-2 mb-4">3. Revenue Summary</h2>
            <div className="space-y-3 text-sm">
              <div className="flex justify-between border-b border-stone-100 pb-1">
                <span className="text-stone-600">Total Valid Revenue</span>
                <span className="font-bold">LKR {data.revenueSummary.totalRevenue.toLocaleString()}</span>
              </div>
              <div className="flex justify-between border-b border-stone-100 pb-1">
                <span className="text-stone-600">Advance Payments Collected</span>
                <span className="font-bold">LKR {data.revenueSummary.advancePayments.toLocaleString()}</span>
              </div>
              <div className="flex justify-between border-b border-stone-100 pb-1">
                <span className="text-stone-600">Final Payments Collected</span>
                <span className="font-bold">LKR {data.revenueSummary.finalPayments.toLocaleString()}</span>
              </div>
              <div className="flex justify-between border-b border-stone-100 pb-1 text-red-600">
                <span>Outstanding Balances</span>
                <span className="font-bold">LKR {data.revenueSummary.outstandingBalance.toLocaleString()}</span>
              </div>
            </div>
          </div>
        </div>

        <PageFooter page={1} />
      </div>


      {/* ================= PAGE 2 ================= */}
      <div className="relative h-[297mm] w-full p-8 bg-white overflow-hidden box-border">
        <PageHeader />

        <div className="grid grid-cols-2 gap-8 mb-10">
          <div>
            <h2 className="text-xl font-serif font-bold text-luxury-emerald-950 border-b border-stone-200 pb-2 mb-4">4. Hall Utilization</h2>
            <table className="w-full text-sm">
              <thead className="bg-luxury-emerald-950 text-white">
                <tr>
                  <th className="p-2 text-left">Hall</th>
                  <th className="p-2 text-right">Bookings</th>
                  <th className="p-2 text-right">Utilization</th>
                </tr>
              </thead>
              <tbody>
                {data.hallStats.map((h: any, i: number) => (
                  <tr key={i} className="border-b border-stone-100">
                    <td className="p-2 font-semibold text-stone-700">{h.name}</td>
                    <td className="p-2 text-right">{h.count}</td>
                    <td className="p-2 text-right font-bold text-luxury-gold-600">{h.utilization}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div>
            <h2 className="text-xl font-serif font-bold text-luxury-emerald-950 border-b border-stone-200 pb-2 mb-4">5. Hall Performance (Revenue)</h2>
            <table className="w-full text-sm">
              <thead className="bg-luxury-emerald-950 text-white">
                <tr>
                  <th className="p-2 text-left">Hall</th>
                  <th className="p-2 text-right">Avg Guests</th>
                  <th className="p-2 text-right">Revenue</th>
                </tr>
              </thead>
              <tbody>
                {[...data.hallStats].sort((a,b)=>b.revenue-a.revenue).map((h: any, i: number) => (
                  <tr key={i} className="border-b border-stone-100">
                    <td className="p-2 font-semibold text-stone-700">{h.name}</td>
                    <td className="p-2 text-right">{h.avgGuests}</td>
                    <td className="p-2 text-right font-bold text-xs">LKR {h.revenue.toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <PageFooter page={2} />
      </div>


      {/* ================= PAGE 3 ================= */}
      <div className="relative h-[297mm] w-full p-8 bg-white overflow-hidden box-border">
        <PageHeader />

        <div className="grid grid-cols-2 gap-8 mb-10">
          <div>
            <h2 className="text-xl font-serif font-bold text-luxury-emerald-950 border-b border-stone-200 pb-2 mb-4">6. Top Packages</h2>
            <table className="w-full text-sm">
              <thead className="bg-luxury-emerald-950 text-white">
                <tr>
                  <th className="p-2 text-left">Package</th>
                  <th className="p-2 text-right">Bookings</th>
                  <th className="p-2 text-right">Revenue</th>
                </tr>
              </thead>
              <tbody>
                {data.topPackages.slice(0, 5).map((p: any, i: number) => (
                  <tr key={i} className="border-b border-stone-100">
                    <td className="p-2 font-semibold text-stone-700 truncate max-w-[150px]">{p.name}</td>
                    <td className="p-2 text-right">{p.count}</td>
                    <td className="p-2 text-right text-xs">LKR {p.revenue.toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div>
            <h2 className="text-xl font-serif font-bold text-luxury-emerald-950 border-b border-stone-200 pb-2 mb-4">7. Extra Services Analysis</h2>
            <table className="w-full text-sm">
              <thead className="bg-luxury-emerald-950 text-white">
                <tr>
                  <th className="p-2 text-left">Service</th>
                  <th className="p-2 text-right">Selected</th>
                  <th className="p-2 text-right">Est. Revenue</th>
                </tr>
              </thead>
              <tbody>
                {data.topServices.slice(0, 5).map((s: any, i: number) => (
                  <tr key={i} className="border-b border-stone-100">
                    <td className="p-2 font-semibold text-stone-700 truncate max-w-[150px]">{s.name}</td>
                    <td className="p-2 text-right">{s.count}</td>
                    <td className="p-2 text-right text-xs">LKR {s.revenue.toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-8 mb-10">
          <div>
            <h2 className="text-xl font-serif font-bold text-luxury-emerald-950 border-b border-stone-200 pb-2 mb-4">8. Customer Statistics</h2>
            <div className="space-y-2 text-sm bg-stone-50 p-4 rounded border border-stone-200 mb-6">
              <div className="flex justify-between border-b border-stone-200 pb-1"><span>Total Customers</span><span className="font-bold">{data.customerStats.totalCustomers}</span></div>
              <div className="flex justify-between border-b border-stone-200 pb-1"><span>New Customers</span><span className="font-bold text-luxury-gold-600">{data.customerStats.newCustomers}</span></div>
              <div className="flex justify-between pb-1"><span>Returning Customers</span><span className="font-bold">{data.customerStats.returningCustomers}</span></div>
            </div>
          </div>
          <div>
            <h2 className="text-xl font-serif font-bold text-luxury-emerald-950 border-b border-stone-200 pb-2 mb-4">9. Payment Analysis</h2>
            <div className="space-y-4 text-sm bg-stone-50 p-4 rounded border border-stone-200 mb-6">
              <div>
                <p className="font-bold text-stone-800 mb-2">By Method</p>
                {data.paymentAnalysis.methods.map((m: any, i: number) => (
                  <div key={i} className="flex justify-between border-b border-stone-200 pb-1 mb-1 text-stone-600">
                    <span>{m.name} ({m.transactions} txns)</span><span>LKR {m.revenue.toLocaleString()}</span>
                  </div>
                ))}
              </div>
              <div>
                <p className="font-bold text-stone-800 mb-2 mt-4">By Type</p>
                {data.paymentAnalysis.types.map((t: any, i: number) => (
                  <div key={i} className="flex justify-between border-b border-stone-200 pb-1 mb-1 text-stone-600">
                    <span>{t.name} ({t.transactions} txns)</span><span>LKR {t.revenue.toLocaleString()}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        <PageFooter page={3} />
      </div>


      {/* ================= PAGE 4 ================= */}
      <div className="relative h-[297mm] w-full p-8 bg-white overflow-hidden box-border">
        <PageHeader />

        <div className="grid grid-cols-2 gap-8 mb-10">
          <div>
            <h2 className="text-xl font-serif font-bold text-luxury-emerald-950 border-b border-stone-200 pb-2 mb-4">10. Cancellation Analysis</h2>
            <div className="space-y-2 text-sm bg-stone-50 p-4 rounded border border-stone-200">
              <div className="flex justify-between border-b border-stone-200 pb-1 text-red-600"><span className="font-bold">Total Cancellations</span><span className="font-bold">{data.cancellationStats.total}</span></div>
              {data.cancellationStats.reasons.map((r: any, i: number) => (
                <div key={i} className="flex justify-between text-stone-600"><span>{r.reason}</span><span>{r.count}</span></div>
              ))}
            </div>
          </div>

          <div>
            <h2 className="text-xl font-serif font-bold text-luxury-emerald-950 border-b border-stone-200 pb-2 mb-4">11. Customer Reviews</h2>
            <div className="flex items-center gap-6 bg-stone-50 p-4 rounded border border-stone-200">
              <div className="text-center">
                <p className="text-4xl font-serif font-bold text-luxury-gold-600">{data.reviewStats.averageRating}</p>
                <p className="text-[10px] uppercase font-bold text-stone-500 tracking-wider">Avg Rating</p>
              </div>
              <div className="flex-1 space-y-1 text-xs">
                {[5, 4, 3, 2, 1].map((stars) => {
                  const count = data.reviewStats.distribution[stars as keyof typeof data.reviewStats.distribution];
                  const pct = data.reviewStats.totalReviews ? (count / data.reviewStats.totalReviews) * 100 : 0;
                  return (
                    <div key={stars} className="flex items-center gap-2">
                      <span className="w-8">{stars} Stars</span>
                      <div className="flex-1 h-2 bg-stone-200 rounded-full overflow-hidden">
                        <div className="h-full bg-luxury-gold-500" style={{ width: `${pct}%` }}></div>
                      </div>
                      <span className="w-6 text-right text-stone-500">{count}</span>
                    </div>
                  )
                })}
              </div>
            </div>
          </div>
        </div>

        {/* Section 12: Business Insights */}
        <div className="mb-10 bg-luxury-emerald-950 text-white p-6 rounded-lg">
          <h2 className="text-2xl font-serif font-bold border-b border-white/20 pb-2 mb-4 text-luxury-gold-400">12. Automated Business Insights</h2>
          <ul className="space-y-3">
            {data.insights.map((insight: string, i: number) => (
              <li key={i} className="flex items-start gap-3 text-sm">
                <span className="text-luxury-gold-500 mt-1">✦</span>
                <span className="leading-relaxed">{insight}</span>
              </li>
            ))}
          </ul>
        </div>

        <PageFooter page={4} />
      </div>

    </div>
  );
});

PrintableReportTemplate.displayName = 'PrintableReportTemplate';
